### ISSUE TITLE
README.md seems out of date

### ISSUE THREAD

**Issue by louaaron** [cipriancorneanu/dnn-topology#1]
Hi all. This is a good work but it seems that the README.md is out of date and not workable. Specifically,

The command to install DIPHA doesn't seem to work.

```
cd ./dipha
cmake -H. .Bbuild
cmake --build build -- -j3
```

and gives me

```
CMake Error: The source directory ".../dnn-topology/dipha/.Bbuild" does not exist.
```

Also it appears that the running file

```
python main.py --net lenet --dataset mnist --trial 0 --lr 0.001  --n_epochs_train 50 --epochs_test '10 20 30 40 50' --graph_type functional --homology_type 'persistent' --train 1 --build_graph 1
```

is not valid. There is no ```main.py``` file and the options do not work for ```train.py```

**Comment by cipriancorneanu** [comment]
I've made an update that should have solved all these issues. Hope you will find helpful.

**Comment by louaaron** [comment]
Thanks!
