### ISSUE TITLE
Question about build_graph_functional.py

### ISSUE THREAD

**Issue by asier-gutierrez** [cipriancorneanu/dnn-topology#2]
Dear Ciprian, your code looks amazing!

We are currently using it for some research but we found a line of code we can not understand. In this step of the code:
https://github.com/cipriancorneanu/dnn-topology/blob/9c50a0883c6bfd92675a67828926196a6f95ffcc/build_graph_functional.py#L59

We do not get why you create two passers. We thought this could be related to reference passing and OOP stuff. We tried removing the "passer_test" variable and operating only with one passer and the results are the same. Is this an unintended code duplication or is it a bug?

Thank you for this interesting work!

**Comment by asier-gutierrez** [comment]
I found out that it is for convention in other similar scripts: https://github.com/cipriancorneanu/dnn-topology/blob/master/build_graph_functional_big_networks.py#L83

**Comment by cipriancorneanu** [comment]
Hi Asier, thanks for the interest. I am currently on vacation and I'll look
into it as soon as I get back, probably next week.

Best,
